language: python
python:
  - "3.9"
branches:
  only:
  - main
  - /^\d+\.\d+\.\d+$/  # Use sem var
install:
  # Print out the version of Python and pip
  - python --version
  - pip --version
  # Install dependencies
  - pip install pipenv
  - pipenv install --dev
script:
  # Linter
  - pycodestyle
  # Unit tests
  - pytest
