language: python
python:
  - "2.7"
install:
  # Print out the version of Python and pip
  - python --version
  - pip --version
  # Install dependencies
  - pip install pipenv
  - pipenv install
script: echo "TEST!"